version: '3.1'

services:
  application:
    build: .
    restart: always
    ports:
      - 8888:8888
    links:
      - db:database
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
    ports:
      - 3306:3306