version: "3.7"

services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
#    networks:
#      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/demo?useSSL=false&allowPublicKeyRetrieval=true
    depends_on:
      mysqldb:
        condition: service_healthy
    
#    volumes:
#      - .m2:/root/.m2
      
  mysqldb:
    image: mysql:latest
#    networks: 
#      - springapimysql-net
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 50s
      timeout: 5s
      retries: 10
networks:
  springapimysql-net:
